/**
 * Created by krizia on 6/13/18.
 */

public with sharing class Console_RightPanelController { //KHB added with sharing
//    public Id theAccountId { get; set; }
//    public Opportunity theOpp { get; set; }

    public Console_RightPanelController(ApexPages.StandardController sc){
        //Get the records for display
//        if (sc.getRecord().getsObjectType() == Opportunity.sObjectType) {
//            Id theOppId = sc.getId();
//
//            theOpp = [
//                    SELECT Id, AccountId
//                    FROM Opportunity
//                    WHERE Id = :theOppId
//                    LIMIT 1
//            ];
//            theAccountId = theOpp.AccountId;
//        } else if (sc.getRecord().getsObjectType() == Account.sObjectType) {
//            theAccountId = sc.getId();
//        }
    } //public Console_RightPanelController()





}