/**
 * Created by krizia on 6/13/18.
 * Console_RightPanelController: 100%
 */
@isTest
public class Console_RightPanelController_TEST {

//    @isTest static void constructor_Test(){
//        Account a = new Account(
//                Name = 'Drover Buck'
//        );
//        INSERT a;
//        Opportunity o = new Opportunity(
//                AccountId = a.Id,
//                Name = 'Max Attack',
//                StageName = 'New Opportunity',
//                CloseDate = System.today().addDays(20)
//        );
//        INSERT o;
//        Task t = new Task(
//                WhatId = o.Id,
//                Patient__c = a.Id,
//                Subject = 'Treat',
//                Description = 'Throw me a bone.',
//                Status = 'Completed'
//        );
//        INSERT t;
//
//        ApexPages.StandardController sc = new ApexPages.StandardController(o);
//        Console_RightPanelController rpc = new Console_RightPanelController(sc);
//
//        System.assert(rpc.theOpp.Id == o.Id);
//        System.assert(rpc.theTasks[0].Id == t.Id);
//    } //@isTest static void constructor_Test()


}